### ISSUE TITLE
enum tag collisions in windows/user32.zig

### ISSUE THREAD

**Issue by ethernetsellout** [Aransentin/ZWL#23]
This library currently doesn't build on Windows, as the WM enum in windows/user32.zig has a few tags that share the same value, namely KEYDOWN and KEYFIRST (0x0100), IME_COMPOSITION and IME_KEYLAST (0x010F), also MOUSEFIRST and MOUSEMOVE (0x0200). 

I got it to build by commenting out KEYFIRST, IME_KEYLAST and MOUSEFIRST, as they were unused. It appears these are just constants indicating the beginning and end of a range of messages and are not intended to be handled, correct me if I'm wrong.

**Comment by Aransentin** [comment]
Should work with #24
